### ISSUE TITLE
Go version reports its version to be always dev

### ISSUE THREAD

**Issue by yermulnik** [dmlittle/scenery#17]
Building `scenery` using `go get …` always reports `dev` version:
```
> go get -v -u github.com/dmlittle/scenery
github.com/dmlittle/scenery (download)
github.com/alecthomas/participle (download)
github.com/fatih/color (download)
github.com/pmezard/go-difflib (download)
github.com/spf13/cobra (download)
github.com/spf13/pflag (download)

> scenery --version
scenery version dev
```

**Comment by dmlittle** [comment]
@yermulnik when you download and install scenery with `go get` you're downloading the source code and the go toolchain is compiling it locally. The built version will be whatever commit is the last commit on the master branch at the time running the command.

I'd like to add the tool on `brew` so people can install specific version without having to install master but it was previously rejected due to scenery being too new (#10). Maybe we can try again. 

That being said, I think the dev version could be improved. Do you thin it'd be better if it also displayed the commit SHA it currently is based off? Something along the lines of `scenery version dev (337c8d7)`

**Comment by yermulnik** [comment]
> Do you thin it'd be better if it also displayed the commit SHA it currently is based off?

This is what I defo thought of. Thanks a bunch =)

ps: if possible and reasonable to have latest released stable `master` version as well

**Comment by dmlittle** [comment]
Currently the [Makefile `build` rule](https://github.com/dmlittle/scenery/blob/337c8d7843cd0f14739f669f2ef273be75a4b8fa/Makefile#L10-L21) injects the build version during compile time using `-ldflags -X main.Version=vX.Y.Z` (this is how the version is set for the [released binaries](https://github.com/dmlittle/scenery/releases)). 

If you run `make build` this should already be working (notice how `make build` inserts the correct version on during compile time).
```bash
> make build
---> Building
CGO_ENABLED=0 go build -o ./bin/scenery -ldflags='-w -s -X "main.Version=v0.1.2"'
> ./bin/scenery --version
scenery version v0.1.2
> echo "func noop() {}" >> main.go
> make build
---> Building
CGO_ENABLED=0 go build -o ./bin/scenery -ldflags='-w -s -X "main.Version=v0.1.2-dev"'
> ./bin/scenery --version
scenery version v0.1.2-dev
> git add .
> git commit -m "test scenery version on non-tagged commit"
[master 94f0416] test scenery version on non-tagged commit
 1 file changed, 1 insertion(+)
> make build
---> Building
CGO_ENABLED=0 go build -o ./bin/scenery -ldflags='-w -s -X "main.Version=v0.1.2-1-g94f0416"'
> ./bin/scenery --version
scenery version v0.1.2-1-g94f0416
```

However when someone runs `go get` the ldflags are not set so the current solution does not work and the [default `"dev"` value](https://github.com/dmlittle/scenery/blob/337c8d7843cd0f14739f669f2ef273be75a4b8fa/main.go#L6) is displayed. 

Go 1.12 was released today and it looks like to solve this very issue they've added [`debug. ReadBuildInfo()`](https://tip.golang.org/pkg/runtime/debug/#BuildInfo). However this only works if you're running Go modules which this project currently doesn't rely on. I'd like to keep using dep until all the issues with Go modules have been ironed out.

An alternative solution would be to bump the `Version` value on every commit/release but that seems somewhat unnecessary and not really valuable. 

Long-term I think the ideal solution for people installing scenery should be through some sort of package manager and not directly through the go toolchain (not everyone running terraform necessary has to have a go working environment locally) unless they plan on developing new features or fixing bugs. I'd love to get the project into Homebrew but that is still up to the its maintainers. If it doesn't get accepted I might run a dedicated tap but ideally it can be added to the core tap.

As for keep `master` stable, that is the current plan. Anything merged into the branch master should be stable; if something is not it's a bug and unintentional. Any new features that aren't stable will be developed in feature branches and only merged once they are stable.
