### ISSUE TITLE
Base64 decoded output for created resources

### ISSUE THREAD

**Issue by robinjoseph08** [dmlittle/scenery#24]
Right now, the base64 parsing of fields is working great, but it seems to only apply to modified resources. If the resource is new/being created, it still just shows the base64 string. It would be nice if created resources also got the base64 fields parsed as well.

**Comment by dmlittle** [comment]
@robinjoseph08 #25 was merged into master which adds the functionality to decode base64 data in created resources. You can get the latest version by running `go get -u github.com/dmlittle/scenery`. 

I'll be cutting a new version sometime this week.
