### ISSUE TITLE
Support empty plans

### ISSUE THREAD

**Issue by tolidano** [dmlittle/scenery#36]
Make this work as it does here:

https://github.com/coinbase/terraform-landscape/search?q=%22This+plan+does+nothing.%22&unscoped_q=%22This+plan+does+nothing.%22

**Comment by tolidano** [comment]
You seem to try to handle it: https://github.com/dmlittle/scenery/blob/13ffc24631751185673cf3c98457830ce1caa8ff/pkg/parser/parser.go#L158

**Comment by tolidano** [comment]
But then this: 

```
18:03 $ terraform show /Users/shawn/dev/environments/test/core/tfplan | scenery
Failed to parse plan. Returning original input.
This plan does nothing.
```

**Comment by tolidano** [comment]
Looks like the lexer may not allow the first character to be "N"

**Comment by dmlittle** [comment]
@tolidano thanks for opening up the issue! I think the regex might have been a little to strict (in this case it's also looking for an extra new-line which I don't think your plan had). I have a branch with a fix [here](https://github.com/dmlittle/scenery/commit/ff4dbe4d48bd74a32166513aaad8d3570460846d).

Can you share the output plan that is causing the failure so I can confirm this fixes the issue? The output of `terraform show /Users/shawn/dev/environments/test/core/tfplan` (you can sensor anything private that might be in the output).

Thanks!

**Comment by tolidano** [comment]
I believe the output is above, your application returns it when failing to parse:
“This plan does nothing.”
It may also say “No changes” depending on version I believe.
Also 0.12 now has -json option which will make it easier hopefully.
