### ISSUE TITLE
Participle lexer dependency not found

### ISSUE THREAD

**Issue by sensedata1** [dmlittle/scenery#42]
Hi there, 

I have some automated builds which rely on scenery, it seems the dependency lexer is not being found where it's expected. 

```
package github.com/alecthomas/participle/v2/lexer: cannot find package "github.com/alecthomas/participle/v2/lexer" in any of:
--
66 | /root/.goenv/versions/1.13.8/src/github.com/alecthomas/participle/v2/lexer (from $GOROOT)
67 | /usr/local/src/github.com/alecthomas/participle/v2/lexer (from $GOPATH)
```

**Comment by dpresling** [comment]
participle v2 has been released so the new path is github.com/alecthomas/participle/lexer

**Comment by dmlittle** [comment]
Scenery is not actively maintained and the repo will be archived momentarily. I no longer have the time to maintain this tool nor do I think it should be kept being used as Terraform 0.11 has been deprecated for over a year now (scenery can only parse Terraform 0.11 plan outputs). Terraform 0.14 has some plan output changes as well as introduced the concept of concise diff plan outputs which does most of what scenery currently does. 

If you'd like to add new functionality as you cannot upgrade your terraform version feel free you fork the repo.
