### ISSUE TITLE
Add support for Markdown Diff

### ISSUE THREAD

**Issue by ghostsquad** [dmlittle/scenery#43]
Looking for something to solve this problem:

https://github.com/runatlantis/atlantis/issues/1395

**Comment by dmlittle** [comment]
Scenery is not actively maintained and the repo will be archived momentarily. I no longer have the time to maintain this tool nor do I think it should be kept being used as Terraform 0.11 has been deprecated for over a year now (scenery can only parse Terraform 0.11 plan outputs). Terraform 0.14 has some plan output changes as well as introduced the concept of concise diff plan outputs which does most of what scenery currently does. 

If you'd like to add new functionality as you cannot upgrade your terraform version feel free you fork the repo.
